services:
  webmushra:
    image: php:7.0-apache
    volumes:
      - ./:/var/www/html
      - ./results:/var/www/html/results
      - ./configs:/var/www/html/configs
    ports:
      - "8000:80"

# Hi!!!
